const basePath = "assets/images";

const walkthrough1 = "$basePath/walkthrough1.png";
const loginLogo = "$basePath/logo/appCircularLogo.png";
const fingerprint = "$basePath/fingerprint.png";
const account = "$basePath/account.png";
const ankara = "$basePath/ankara.png";
const dispatchRider = "$basePath/bikeman.png";
const catalogue = "$basePath/catalogue.png";
const fabric = "$basePath/fabric.png";
const femaleAsoebi = "$basePath/female-asoebi.png";
const maleAsoebi = "$basePath/male-asoebi.png";
const homeIcon = "$basePath/homepage.png";
const man = "$basePath/man.png";
const sewingMachine = "$basePath/sewing-machine.png";
const carouselBg = "$basePath/carouselBg.jpg";
const favoriteIcon = "$basePath/favorite.png";
const notificationIcon = "$basePath/notificationIcon.png";
const menuIcon = "$basePath/home-menu.png";
const homeLogo = "$basePath/logo/home-logo.png";
const backIcon = "$basePath/back-icon.png";
const activity = "$basePath/activity.png";
const becomeVendor = "$basePath/become-vendor.png";
const chats = "$basePath/chats.png";
const chatIcon = "$basePath/chat-icon.png";
const orders = "$basePath/orders.png";
const settings = "$basePath/Settings-icon.png";
const shareEarn = "$basePath/share-earn.png";
const support = "$basePath/support.png";
const wallet = "$basePath/wallet.png";
const walletBg = "$basePath/walletbg.png";
const profileIcon = "$basePath/profileIcon.png";
const helpIcon = "$basePath/help.png";
const filterIcon = "$basePath/filter.png";
const uploadIcon = "$basePath/upload.png";
const profileAvatar = "$basePath/profile-avatar.png";
const downArrow = "$basePath/down-arrow.png";
const kycIcon = "$basePath/kyc-icon.png";
const forwardArrow = "$basePath/arrow.png";
const bizImage = "$basePath/business-image.png";
const clock = "$basePath/clock.png";
const readyToWear = "$basePath/ready-to-wear.png";
const cardIcon = "$basePath/card.png";
const ussdIcon = "$basePath/ussd.png";
const transferIcon = "$basePath/transfer.png";
const cashIcon = "$basePath/cash.png";
const creditIcon = "$basePath/credit.png";
const debitIcon = "$basePath/debit.png";
const paymentIcon = "$basePath/payment.png";
const logoutIcon = "$basePath/logout.png";
const savedIcon = "$basePath/saved.png";
const styleitIcon = "$basePath/styleit.png";

// Categories
const catAnkara = "$basePath/categories/ankaraFabric.png";
const catFemaleAsoEbi = "$basePath/categories/femaleAsoEbi.png";
const catLace = "$basePath/categories/lace.png";
const catMaleAsoEbi = "$basePath/categories/maleAsoEbi.png";
const catMaterials = "$basePath/categories/materials.png";
const catReadyToWear = "$basePath/categories/readyToWear.png";
const catSenator = "$basePath/categories/senatorStyles.png";

// User
const defaultUserImage = "assets/images/user/1.png";
// Account Section Themes
const moneyTheme = "$basePath/accountsection/moneytheme.png";
const economyTheme = "$basePath/accountsection/economytheme.png";
